// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmwtlajcbmlundzqihhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imptd3RsYWpjYm1sdW5kenFpaGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTQ5NjksImV4cCI6MjA3MTAzMDk2OX0.JKFEyCHS1yRflvgiW_L2OxKnGLnWNuNtwDy5QFcAFU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});